---
services:
  lancommander:
    image: ghcr.io/lancommander/lancommander:latest
    container_name: lancommander
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 1337:1337
    restart: unless-stopped
