# The port LANCommander should listen on (HTTP)
Port: 1337

# Broadcast the server's address on the local network to be picked up by clients
Beacon: True

# Change this!
TokenSecret: abcdefghijklmnopqrstuvwxyz123456790

# How long the token is valid for (in days)
TokenLifetime: 30

# Probably want to leave this alone
DatabaseConnectionString: Data Source=LANCommander.db;Cache=Shared

# IGDB Credentials: https://api-docs.igdb.com/#getting-started
IGDBClientId: abcdefghijklmnopqrstuvwxyz123456790
IGDBClientSecret: abcdefghijklmnopqrstuvwxyz123456790