on: [push]

env:
    REGISTRY: ghcr.io

jobs:
      push-lancommander-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './Docker'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@v4
          - name: lowercase github.repository
            run: |
              echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}
          - name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          - name: Build and Push Latest Docker Image
            id: build-and-push-latest
            uses: docker/build-push-action@v5
            if: ${{ github.ref == 'refs/heads/main' }}
            with:
              context: Docker
              push: true
              tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
              labels: ${{ steps.meta.outputs.labels }}
