name: LANCommander Release

on:
  push:
    tags:
      - 'v*'
jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    # Server
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "./LANCommander/LANCommander.csproj" --no-restore
    - name: Publish
      run: dotnet publish "./LANCommander/LANCommander.csproj" -c Release -o _Build --self-contained --os win -p:PublishSingleFile=true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LANCommander-${{ github.event.release.tag_name }}
        path: "./_Build"
    # Client
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
    - name: Restore NuGet packages
      run: nuget restore LANCommander.sln
    - name: Build and Publish Library
      run: msbuild LANCommander.Playnite.Extension/LANCommander.PlaynitePlugin.csproj /p:Configuration=Release /p:OutputPath=Build
    - name: Download Playnite Release
      uses: robinraju/release-downloader@v1.7
      with:
        repository: JosefNemec/Playnite
        tag: 10.18
        fileName: Playnite1018.zip
    - name: Extract Playnite
      run: Expand-Archive -Path Playnite1018.zip -DestinationPath Playnite
    - name: Run Playnite Toolbox
      run: Playnite/Toolbox.exe pack LANCommander.Playnite.Extension/Build .
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: LANCommander.PlaynitePlugin-${{ github.event.release.tag_name }}
        path: LANCommander.PlaynitePlugin_48e1bac7-e0a0-45d7-ba83-36f5e9e959fc_1_0.pext
    # Release
    
