name: LANCommander Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # Server
  build_server_linux-arm64:
    uses: ./.github/workflows/LANCommander.Server.Linux.arm64.yml
  build_server_linux-x64:
    uses: ./.github/workflows/LANCommander.Server.Linux.x64.yml
  build_server_osx-arm64:
    uses: ./.github/workflows/LANCommander.Server.macOS.arm64.yml
  build_server_osx-x64:
    uses: ./.github/workflows/LANCommander.Server.macOS.x64.yml
  build_server_win-arm64:
    uses: ./.github/workflows/LANCommander.Server.Windows.arm64.yml
  build_server_win-x64:
    uses: ./.github/workflows/LANCommander.Server.Windows.x64.yml

  # Launcher
  build_launcher_linux-arm64:
    uses: ./.github/workflows/LANCommander.Launcher.Linux.arm64.yml
  build_launcher_linux-x64:
    uses: ./.github/workflows/LANCommander.Launcher.Linux.x64.yml
  build_launcher_osx-arm64:
    uses: ./.github/workflows/LANCommander.Launcher.macOS.arm64.yml
  build_launcher_osx-x64:
    uses: ./.github/workflows/LANCommander.Launcher.macOS.x64.yml
  build_launcher_win-arm64:
    uses: ./.github/workflows/LANCommander.Launcher.Windows.arm64.yml
  build_launcher_win-x64:
    uses: ./.github/workflows/LANCommander.Launcher.Windows.x64.yml

  build_release:
    runs-on: windows-latest
    needs: [build_server_linux-arm64, build_server_linux-x64, build_server_osx-arm64, build_server_osx-x64, build_server_win-arm64, build_server_win-x64, build_launcher_linux-arm64, build_launcher_linux-x64, build_launcher_osx-arm64, build_launcher_osx-x64, build_launcher_win-arm64, build_launcher_win-x64]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: frabert/replace-string-action@v2
      name: Trim Tag Ref
      id: trim_tag_ref
      with:
        string: '${{ github.ref }}'
        pattern: 'refs/tags/v'
        replace-with: ''

    - uses: frabert/replace-string-action@v2
      name: Swap Path Backslashes
      id: swap_path_backslashes
      with:
        string: '${{ github.workspace }}'
        pattern: '\\'
        replace-with: '/'
        flags: g

    # Draft Release
    - name: Download Server Linux ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-Linux-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Server Linux x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-Linux-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Server macOS ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-macOS-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Server macOS x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-macOS-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Server Windows ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-Windows-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Server Windows x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Server-Windows-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher Linux ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-Linux-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher Linux x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-Linux-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher macOS x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-macOS-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher macOS ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-macOS-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher Windows ARM64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-Windows-arm64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
    - name: Download Launcher Windows x64
      uses: actions/download-artifact@v3
      with:
        name: LANCommander.Launcher-Windows-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip

    - name: Draft Release
      uses: softprops/action-gh-release@v2
      with:
        name: v${{ steps.trim_tag_ref.outputs.replaced }}
        generate_release_notes: true
        draft: true
        files: |
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-Windows-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-Windows-x64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-Linux-x64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-Linux-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-macOS-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Server-macOS-x64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-Windows-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-Windows-x64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-Linux-x64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-Linux-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-macOS-arm64-*.zip
          ${{ steps.swap_path_backslashes.outputs.replaced }}/LANCommander.Launcher-macOS-x64-*.zip