name: LANCommander Launcher Windows x64

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: frabert/replace-string-action@v2
      name: Trim Tag Ref
      id: trim_tag_ref
      with:
        string: '${{ github.ref }}'
        pattern: 'refs/tags/v'
        replace-with: ''

    - uses: frabert/replace-string-action@v2
      name: Swap Path Backslashes
      id: swap_path_backslashes
      with:
        string: '${{ github.workspace }}'
        pattern: '\\'
        replace-with: '/'
        flags: g

    # dotnet
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore Packages
      run: nuget restore

    - name: Restore dependencies
      run: dotnet restore

    # Auto Updater
    - name: Publish Updater
      run: dotnet publish "./LANCommander.AutoUpdater/LANCommander.AutoUpdater.csproj" -c Release --self-contained --runtime win-x64 -p:Version="${{ steps.trim_tag_ref.outputs.replaced }}" -p:AssemblyVersion="${{ steps.trim_tag_ref.outputs.replaced }}"
    - name: Rename Updater
      run: mv ./LANCommander.AutoUpdater/bin/Release/net8.0/win-x64/publish/LANCommander.AutoUpdater.exe ./LANCommander.AutoUpdater/bin/Release/net8.0/win-x64/publish/LANCommander.AutoUpdater.exe.Update
    
    # UI
    - run: cd ./LANCommander.UI; npm install; npm run package

    # Launcher
    - run: cd LANCommander.Launcher; npm install

    - name: Publish Launcher
      run: dotnet publish "./LANCommander.Launcher/LANCommander.Launcher.csproj" -c Release --self-contained --runtime win-x64 -p:Version="${{ steps.trim_tag_ref.outputs.replaced }}" -p:AssemblyVersion="${{ steps.trim_tag_ref.outputs.replaced }}"

    # CLI
    - run: cd ./LANCommander.Launcher.CLI

    - name: Publish CLI
      run: dotnet publish "./LANCommander.Launcher.CLI/LANCommander.Launcher.CLI.csproj" -c Release --self-contained --runtime win-x64 -p:Version="${{ steps.trim_tag_ref.outputs.replaced }}" -p:AssemblyVersion="${{ steps.trim_tag_ref.outputs.replaced }}"

    - name: Remove Extra Files
      run: |
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/BootstrapBlazor.PdfReader/compat
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/BootstrapBlazor.PdfReader/2.*
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/BootstrapBlazor.PdfReader/build/pdf.sandbox.js
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/BootstrapBlazor.PdfReader/build/*.map
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/BootstrapBlazor.PdfReader/web/*.map
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/wwwroot/_content/AntDesign/less
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/LANCommander.ico
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/LANCommanderDark.ico
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/package-lock.json
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/package.json
        rm -Recurse -Force -ErrorAction Ignore ./LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/*.pdb

    # Create ZIP file
    - name: Package Launcher Build
      uses: vimtor/action-zip@v1.2
      with:
        files: LANCommander.Launcher/bin/Release/net8.0/win-x64/publish/ LANCommander.AutoUpdater/bin/Release/net8.0/win-x64/publish/ LANCommander.Launcher.CLI/bin/Release/net8.0/win-x64/LANCommander.Launcher.CLI.exe
        recursive: true
        dest: LANCommander.Launcher-Windows-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        path: LANCommander.Launcher-Windows-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip
        name: LANCommander.Launcher-Windows-x64-v${{ steps.trim_tag_ref.outputs.replaced }}.zip